---

#
# execute local provision
#

- hosts: localhost
  remote_user: cluster

  pre_tasks:
    - include_vars: vars/vars_common.yml
    - include_vars: vars/vars_slave.yml

  roles:
    - common
    - slave
    - nagios_slave
    - hadoop_slave
    - hbase_slave
    - cassandra_slave

  post_tasks:
    - meta: refresh_inventory
