---

- hosts: localhost

  pre_tasks:
    - include_vars: vars/vars_common.yml
    - include_vars: vars/vars_singlenode.yml

  roles:
    - common
    - singlenode
    - hadoop_master
    - hbase_master
    - cassandra_master

# vim: ft=ansible
