---

- name: Start services
  hosts: localhost
  pre_tasks:
    - include_vars: vars/vars_common.yml

  tasks:
    - name: Restart Nagios service
      service: name=nagios state=restarted
      become: yes

    - name: Start Hadoop DFS daemons
      command: sbin/start-dfs.sh chdir={{ hadoop_home_dir }}

    - name: Start Hadoop Yarn
      command: sbin/start-yarn.sh chdir={{ hadoop_home_dir }}

    - name: Start HBase
      command: ./bin/start-hbase.sh chdir={{ hbase_home_dir }}

    - name: Start Thrift server
      command: ./bin/hbase-daemon.sh start thrift chdir={{ hbase_home_dir }}

# vim: ft=ansible