---

user: 'cluster'

#
# master credentials
#
ssh_key: '{{ansible_env.HOME}}/.ssh/id_rsa'
master_hostname: ''
master_ip: ''

#
# hadoop settings
#
hadoop_major_version: 2
hadoop_release: '2.6.3'
hadoop_archive: 'hadoop-{{ hadoop_release }}.tar.gz'
hadoop_base_dir: '{{ ansible_env.HOME }}'
hadoop_home_dir: '{{hadoop_base_dir}}/hadoop-{{hadoop_release}}'
hadoop_tmp_dir: '/data/hadoop'
hadoop_fs_default_name: 'hdfs://{{ master_hostname }}:54310'
hadoop_url: 'https://archive.apache.org/dist/hadoop/core/hadoop-{{ hadoop_release }}/{{ hadoop_archive }}'

#
# hbase settings
#
hbase_release: '1.1.5'
hbase_archive: 'hbase-{{ hbase_release }}-bin.tar.gz'
hbase_base_dir: '{{ ansible_env.HOME }}'
hbase_home_dir: '{{ hbase_base_dir }}/hbase-{{hbase_release}}'
hbase_data_dir: '/data/hbase'
hbase_url: 'https://archive.apache.org/dist/hbase/{{ hbase_release }}/{{ hbase_archive }}'
zookeeper_data_dir: '/data/zk'

#
# cassandra settings
#
cass_release: '3.7'
cass_archive: 'apache-cassandra-{{ cass_release }}-bin.tar.gz'
cass_base_dir: '{{ ansible_env.HOME }}'
cass_home_dir: '{{ cass_base_dir }}/apache-cassandra-{{ cass_release }}'
cass_main_data_dir: '{{ cass_home_dir}}/data'
cass_hints_dir: '{{ cass_main_data_dir }}/hints'
cass_data_dir: '{{ cass_main_data_dir }}/data'
cass_commit_dir: '{{ cass_main_data_dir }}/commitlog'
cass_cached_dir: '{{ cass_main_data_dir }}/saved_caches'
cass_log_dir: '{{ cass_home_dir }}/logs'
cass_url: 'https://archive.apache.org/dist/cassandra/{{ cass_release }}/{{ cass_archive}}'
cass_cluster_name: ''

#
# Route to ansible groups definitions
#
ansible_hosts_file: '/etc/ansible/hosts'
